# PINN ODE SOLVER - options and search space

# Available Components
available_components:
  problem_classes:
    - "ExpDecay"
    - "LogisticGrowth"
    - "HarmonicOscillator"
  model_classes:
    - "MLP"
    - "ResNetMLP"
  activations:
    - "Tanh"
    - "SiLU"
    - "ReLU"

# Global Training Settings
global_settings:
  epochs: 8000
  start: 0.0
  stop: 5.0
  input_dim: 1
  output_dim: 1

# Hyperparameter Search Space
search_space:
  problem_class: ["ExpDecay", "LogisticGrowth", "HarmonicOscillator"]
  model_class: ["MLP", "ResNetMLP"]
  learning_rate: [0.005, 0.001, 0.0005]
  width: [32, 64, 128]
  hidden_dim: [3, 4, 5]
  activation: ["Tanh", "SiLU"]
  ode_loss_weight: [1.0, 5.0, 10.0]
  ic_loss_weight: [1.0, 5.0, 10.0]
